### PR TITLE
Disallow additional properties (Fix #25)

### LINKED ISSUE #25: Restrict additional properties for publish.mson
At the moment it's possible to send "extra" attributes that are not specified in the `publish.mson`. Setting `additionalProperties` to false for each data structure should solve this.
Something like `@schema['additionalProperties'] = false` in [here](https://github.com/moviepilot/lacerda/blob/master/lib/lacerda/conversion/data_structure.rb#L40).

This is a breaking change, as afterwards validation will fail for objects with extra attributes.

### PR DESCRIPTION
**Pull request by dgmora**
After these changes if you add a random property that is not in the contract and try to publish, a validation error will be raised. So you can only publish fields that are specified in the contract.
**This is a breaking change**

### CODE REVIEW

File: spec/lib/lacerda/conversion_spec.rb [hunk 1]
```diff
@@ -135,7 +135,7 @@
       end
 
       context "have properties with custom types that is" do
-        let(:valid_post){ {'id' => 1, 'title' => 'Servus', 'author_id' => 22, 'body' => 'We were somewhere around barstow on the edge of the desert', comments: [] } }
```
Comment (dgmora) [inline spec/lib/lacerda/conversion_spec.rb]: These fields were not in the contract

File: spec/lib/lacerda/service_spec.rb [hunk 2]
```diff
@@ -145,7 +146,7 @@
     end
 
     context "to consume" do
-      let(:valid_post) { {id: 1, title: 'My title'} }
```
Comment (dgmora) [inline spec/lib/lacerda/service_spec.rb]: id field was not in the contract

**Comment by dgmora** [comment]
(Tests failing should be fixed by #27)

**Comment by jayniz** [comment]
> (Tests failing should be fixed by #27)

**Comment by dgmora** [comment]
[Apparently](https://github.com/moviepilot/lacerda/pull/28/files#diff-93830fa29d616f7c87903d08b5b1b29aR7) I really like breaking things again
